# numpy

In [1]:
import numpy as np
a = np.array([3,4,5]) #creating arrays

### accessing the array


In [2]:
a[0]

3

In [3]:
a[1]

4

In [4]:

a[2]

5

this is two dimension array

In [8]:
a = np.array([[1,2],[3,4],[5,6]])

#### get the dimension,itemsize/bytesize,data type,total number of elements

In [9]:
#to print the type dimensions
a.ndim

2

In [11]:
a.itemsize #prints the byte size,for a we have got integer elements hence 4 bytes

4

In [12]:
a.dtype #gives the data type

dtype('int32')

In [15]:
#to get the size,it doesn't matter the dimension but the total number of elements
a.size

6

In [16]:
a.shape #to get the shape of demension

(3, 2)

In [17]:
a #as I see here it has 3 rows and 2columns

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

#### initialize the array as a float or complex number

In [14]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.float64) #64 means occupy 8 bytes
a.itemsize

8

In [19]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

### initialize your array with zeros

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### initialize with ones

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### create array using range

In [27]:
range(1,6)

range(1, 6)

In [28]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

#### creating array using arange while skipping some values in a series

In [30]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

#### generate other numbers in between number range specified

In [31]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

#### reshaping your arrays

In [35]:
a = np.array([[1,2],[3,4],[5,6]])
a.shape

(3, 2)

In [36]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [39]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

#### the ravel function to flatten the array

In [40]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

#### min, max and sum

In [41]:
a.min()

1

In [42]:
a.max()

6

In [43]:
a.sum()

21

#### axis 1 and axis 0 sum

In [45]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
## 1,3,5 and 2,4,6 -> axis 0

In [47]:
a.sum(axis=0)

array([ 9, 12])

In [48]:
## 1,2 and 3,4 and 5,6 -> axis 1

In [49]:
a.sum(axis=1)

array([ 3,  7, 11])

#### find the sqrt of all elements

In [50]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

#### find the standard deviation

In [51]:
np.std(a)

1.707825127659933

### basic math operation

In [54]:
a=np.array([[1, 2], [3, 4]])
b=np.array([[5, 6], [7, 8]])

###### adding,dividing and multiplying two arrays together

In [55]:
a+b

array([[ 6,  8],
       [10, 12]])

In [56]:
a*b

array([[ 5, 12],
       [21, 32]])

In [57]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

##### a matrix product

In [58]:
a.dot(b)

array([[19, 22],
       [43, 50]])